### ISSUE TITLE
EntityID list in group

### ISSUE THREAD

**Issue by Pulpyyyy** [rstrouse/ESPSomfy-RTS-HA#16]
Hello,

ESPSomfy-RTS group mechanism is working fine and you did a good job.
I'm just missing a feature :
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/32004297/b1a8c32a-2057-4a10-81ce-35aacb2c5463)
As you can see `cover.volets_salon` does have an extra `entity_id` attribute with the cover's ID list when defined as cover group in HA yaml config.
```
cover:
  - platform: group
    name: "volets_salon"
    entities:
      - cover.volet_salon_allee
      - cover.volet_salon_rue
```
ID list is already available in ESPSomfy-RTS UI
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/32004297/a0fa62af-5749-4db4-bffd-cf328a66f56c)

May this be added as a new feature ?

Many thanks
