### ISSUE TITLE
Sending StepUp and StepDown

### ISSUE THREAD

**Issue by perfrankling** [rstrouse/ESPSomfy-RTS-HA#32]
I would need to be able to send StepUp and StepDown commands to my blinds based on button presses from my wall buttons, but there does not seem to be HA Services for ESPSSomfy RTS for that.

(I have KNX buttons. With long presses I want to start moving the blinds to the top or bottom, and with short presses I want to stop the blinds and adjust the tilt. The buttons send separate events for long and short presses.)

**Comment by rstrouse** [comment]
You can use the ESPSomfyRTS: Send command service

```yaml
service: espsomfy_rts.send_command
target:
  entity_id: cover.left_shade
  device_id: f91b42acffca0d28db58c8adf7041bf8
data:
  command: StepUp

```
